context:
  version: "0.26.0"

package:
  name: agent-browser
  version: ${{ version }}

source:
  url: https://github.com/vercel-labs/agent-browser/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e1852f8fc953763d4482b107a201226413d78d701065a26758f3c3d0b6dc2ad8

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd ./cli
      - if: unix
        then:
          - cargo auditable install --no-track --locked --root $PREFIX --path .
        else:
          - cargo auditable install --no-track --locked --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - agent-browser --version
  - package_contents:
      bin:
        - agent-browser
      strict: true

about:
  homepage: https://github.com/vercel-labs/agent-browser
  summary: Browser automation CLI for AI agents
  description: |
    Browser automation CLI for AI agents. Fast native Rust CLI.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://agent-browser.dev
  repository: https://github.com/vercel-labs/agent-browser

extra:
  recipe-maintainers:
    - yuikisaito
